In [1]:
import numpy as np
import pandas as pd

### DATA

In [2]:
movies = pd.read_csv("datasets/tmdb_5000_movies.csv")
credits = pd.read_csv("datasets/tmdb_5000_credits.csv")

### PREPROCESSING

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
movies = movies.merge(credits,on='title')

In [5]:
movies.info()

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [7]:
movies.dropna(inplace=True)
movies.duplicated().sum()

np.int64(0)

In [8]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [9]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action' , Adventure , Fantasy , scifi]

#its your string of list we have to convert this into list 
# import ast (and write ast.litral_eval(obj) in place of only obj )

In [10]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [11]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [12]:
movies['genres']=movies['genres'].apply(convert)
movies['keywords']=movies['keywords'].apply(convert)

In [13]:
# movies.head()

In [14]:
def convert_top_5(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 5:  # Changed from 3 to 5
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [15]:
movies['cast']=movies['cast'].apply(convert_top_5)

In [16]:
# movies.head()

In [17]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

movies['crew']=movies['crew'].apply(fetch_director)

In [18]:
# movies.head()

In [19]:
movies['overview'][0]
# its a string we wanna convert this in the list so that we can contatinate with other lists
# the function name is lamda

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [20]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [21]:
# movies.head()

In [22]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [23]:
# movies.head()

In [24]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [26]:
new_df = movies[['movie_id','title','tags']]
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

C:\Users\bhuve\AppData\Local\Temp\ipykernel_7616\1025697696.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [27]:
# UPDATE THIS CELL IN YOUR NOTEBOOK
new_df = movies[['movie_id', 'title', 'tags', 'genres', 'cast', 'crew']]

# Keep your existing code underneath it:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\bhuve\AppData\Local\Temp\ipykernel_7616\1470572694.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
C:\Users\bhuve\AppData\Local\Temp\ipykernel_7616\1470572694.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [28]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez jamescameron'

In [29]:
# Text to vector conversion 
# we will recommend those movies which has lower angle with movie is on going
# it called text vectorization
# type of text vectorization
# we gonna use bag of words.(other ar - tfidf , word2vec)

In [30]:
# for words like love, loved, loving etc we will use stemming (PorterStemmer) to convert all these words into one word (love) so that we can get better results

In [31]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [32]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [33]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\bhuve\AppData\Local\Temp\ipykernel_7616\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()

In [35]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [36]:
feature_names = cv.get_feature_names_out()
print(f"Total features: {len(feature_names)}")
print('\n'.join(feature_names))

Total features: 5000
000
007
10
100
11
12
13
14
15
16
17
17th
18
18th
19
1910
1920
1930
1940
1944
1950
1950s
1960
1960s
1970
1970s
1971
1974
1976
1980
1985
1990
1999
19th
19thcenturi
20
200
2003
2009
20th
21st
23
24
25
30
300
3d
40
50
500
60
70
aaron
aaroneckhart
aarontaylor
abandon
abduct
abigailbreslin
abil
abl
aboard
abov
abus
academi
accept
access
accid
accident
acclaim
accompani
accomplish
account
accus
ace
achiev
act
action
actionhero
activ
activist
activities
actor
actress
actual
adam
adambrodi
adamsandl
adamscott
adamshankman
adapt
add
addict
adjust
admir
admit
adolesc
adopt
ador
adrienbrodi
adult
adulteri
adulthood
advanc
adventur
adventure
advertis
advic
advis
affair
affect
afghanistan
africa
african
africanamerican
aftercreditssting
afterlif
aftermath
ag
age
agediffer
agency
agenda
agent
agents
aggress
ago
agre
ahead
aid
aidanquinn
ail
aim
air
airplan
airplanecrash
airport
aka
al
alabama
alan
alanalda
alanarkin
alanrickman
alaska
albert
albertbrook
alcatraz
alcohol
alecbaldwin
alecguin
alex
alexisbledel
alexkendrick
alfredhitchcock
alfredmolina
alfrewoodard
ali
alic
alice
alicebraga
alien
alieninvas
alienlife
alienplanet
aliens
alik
alilart
aliv
alive
allen
alli
allianc
allisonjanney
allow
alon
alongsid
alpacino
alpha
alreadi
alter
altern
alway
alzheimer
amanda
amandapeet
amandaseyfri
amateur
amaz
ambassador
amberheard
ambit
ambiti
ambul
ambush
america
american
americanabroad
americanfootbal
amid
amidst
amnesia
amp
amsterdam
amus
amusementpark
amy
amyadam
amysmart
analyst
anarchiccomedi
ancient
ancientrom
ancientworld
anderson
andi
andiemacdowel
andrew
android
andy
andygarcía
andyserki
angel
angelabassett
angeles
angelinajoli
anger
angle
angri
ani
anim
animalattack
animalhorror
animals
anjelicahuston
ann
anna
annafari
annakendrick
annapaquin
annasophiarobb
anne
annehathaway
annehech
annemoss
annetteben
anni
annie
announc
annual
anonym
anoth
answer
ant
antholog
anthoni
anthonyanderson
anthonyhopkin
anthonymacki
anthropomorph
anti
antihero
antoinefuqua
antoniobandera
antonyelchin
anyon
anyth
apart
apartheid
apartment
ape
apocalyps
apocalypt
appar
appear
appl
appoint
appreci
apprentic
approach
april
arab
arch
archaeologist
archeolog
archer
architect
arctic
area
aren
arena
argument
aris
aristocrat
arm
armi
armiehamm
armor
armsdeal
army
arnold
arnoldschwarzenegg
arrang
arrangedmarriag
arrest
arriv
arrog
art
arthur
artifact
artifici
artificialintellig
artist
ash
ashley
ashleyjudd
ashtonkutch
asia
asian
asid
ask
aspect
aspir
assassin
assault
assembl
assign
assist
assistant
associ
assum
asteroid
astronaut
asylum
athlet
atom
atomicbomb
attack
attacks
attempt
attend
attent
attic
attitud
attorney
attract
auction
audienc
audit
august
aunt
austin
australia
australian
author
autism
auto
automobilerac
aveng
averag
avoid
await
awak
awaken
awar
award
away
awkward
awri
awry
ax
babe
babi
baby
bachelor
backdrop
background
backpack
bad
bag
bahama
bail
bailey
balanc
ball
ballet
balloon
baltimor
ban
band
bandit
bangkok
banish
bank
banker
bankrobb
bankrobberi
bar
barbarahershey
barbrastreisand
bare
bargain
barn
barney
baron
barri
barrylevinson
barrypepp
barrysonnenfeld
bas
base
basebal
basedoncomicbook
basedongraphicnovel
basedonnovel
basedonplay
basedonstagemus
basedontrueev
basedontruestori
basedontvseri
basedonvideogam
basedonyoungadultnovel
basement
basketbal
basketball
bat
batman
battl
battle
battlefield
bay
beach
bear
beast
beat
beauti
beautiful
beautifulwoman
beauty
becam
becaus
becom
becominganadult
bed
bedroom
beer
befor
befriend
began
begin
begins
behavior
belief
believ
bell
bella
belong
belov
ben
benaffleck
bend
beneath
benefit
benfost
beniciodeltoro
benjamin
benjaminbratt
benkingsley
bennett
benstil
bent
berlin
berniemac
best
bestfriend
bet
beth
betray
bettemidl
better
betti
beverli
bibl
big
bigger
biggest
biker
bikini
billhad
billi
billionair
billmurray
billnighi
billpaxton
billpullman
billybobthornton
billyconnolli
billycrudup
billycryst
biographi
biolog
bird
birth
birthday
bisexu
bishop
bit
bite
bitter
bizarr
black
blackmag
blackmail
blackpeopl
blacksmith
blade
blame
blend
blind
bliss
block
blond
blood
bloodi
bloodsplatt
bloodthirsti
blow
blue
board
boardingschool
boat
bob
bobbi
bobbyfarrelli
bobhoskin
bodi
body
bodyguard
bold
bollywood
bomb
bond
bone
bonniehunt
book
border
bore
boredom
born
boss
boston
botch
bound
boundari
bounti
bountyhunt
box
boxer
boy
boyfriend
boys
braddourif
bradleycoop
bradpitt
brain
brand
brandon
brave
braveri
brazil
brazilian
break
breakdown
breakup
breast
breath
breckinmey
breed
brendanfras
brendangleeson
brent
brettratn
brian
briancox
briandennehi
briandepalma
bride
bridesmaid
bridg
brief
brielarson
brien
bright
brilliant
bring
brink
britain
british
britishsecretservic
brittanymurphi
broadcast
broadway
broke
broken
broker
bronx
brook
brooklyn
broom
brothel
brother
brotherbrotherrelationship
brothers
brothersisterrelationship
brought
brown
bruce
brucecampbel
brucedern
brucegreenwood
brucemcgil
brucewilli
brutal
bryansing
brycedallashoward
bu
buck
bud
buddi
buddy
buddycomedi
buddycop
budget
build
building
built
bullet
bulli
bumbl
bunch
bunker
bunni
burglar
buri
burn
burtreynold
bush
busi
business
businessman
bust
butcher
butler
butt
button
buy
buzz
cabin
caesar
cage
cairo
cal
california
calvin
camcord
came
camera
cameraman
cameron
camerondiaz
camgigandet
camp
campaign
campbell
campbellscott
campu
canada
canadian
cancer
candid
canin
cannib
capabl
capit
capt
captain
captiv
captur
car
caraccid
carchas
carcrash
card
care
career
carefre
caretak
careymulligan
caribbean
carjourney
carl
carlagugino
carmen
carol
carolina
carrac
carri
carrie
cartel
carter
cartoon
caryelw
case
caseyaffleck
cash
casino
cast
castl
cat
cataclysm
catastroph
catch
cateblanchett
catherinekeen
catherineo
catherinezeta
cathol
catholic
cattl
caught
caus
cavalri
cave
cedrictheentertain
celebr
cellphon
cemeteri
center
central
centuri
centuries
century
certain
chad
chain
chainsaw
challeng
champion
championship
chanc
chance
chang
change
changes
channingtatum
chao
chaos
chaotic
chapter
charact
character
characters
charg
charismat
charl
charless
charli
charlie
charliesheen
charlizetheron
charlotterampl
charm
chart
chase
chauffeur
chazzpalminteri
cheat
check
cheerlead
chef
chemic
cher
chevychas
chicago
chicken
chief
child
childabus
childhero
childhood
childprodigi
children
chill
chimcbrid
chimp
china
chines
chip
chipmunk
chiwetelejiofor
chloe
chloëgracemoretz
chloësevigni
chocol
choic
choice
choos
chosen
chowyun
chri
chriscolumbu
chriscoop
chrisevan
chrishemsworth
chrisklein
chriso
chrispin
chrispratt
chrisrock
christ
christian
christianbal
christianslat
christin
christinaappleg
christinaricci
christma
christmas
christmasparti
christmastre
christoph
christopherlloyd
christophermcdonald
christophernolan
christopherplumm
christopherwalken
christophwaltz
chrisweitz
chronicl
chuck
church
cia
ciaránhind
cigarettesmok
cillianmurphi
cinema
circl
circu
circuit
circumst
citi
citizen
city
civil
civilian
civilwar
claim
clair
clairedan
claireforlani
clan
clark
clash
class
classic
classmat
classroom
claudevandamm
clay
clean
clear
clerk
client
cliffcurti
climat
climb
clinteastwood
cliveowen
clock
clone
clorisleachman
close
closer
cloud
clown
club
clue
clutch
coach
coast
cocain
code
coffin
cohen
col
cold
coldwar
cole
colehaus
colin
colinfarrel
colinfirth
collaps
colleagu
collect
collector
colleg
college
collid
collin
collis
colombia
colonel
coloni
color
colorado
coma
combat
combin
come
comeback
comed
comedi
comedian
comedy
comet
comfort
comic
coming
comingofag
comingout
command
commando
commerci
commiss
commit
common
commun
communist
community
compani
companion
company
compet
competit
competition
complet
complex
complic
compos
compuls
comput
computerviru
conan
concern
concert
concoct
condit
condition
conduct
confeder
confess
confid
confin
conflict
confront
confus
congress
conman
connect
connecticut
connel
connienielsen
connor
conquer
consequ
consequences
conserv
consid
conspir
conspiraci
conspiracy
constant
constantli
construct
consum
contact
contain
contemporari
contend
contest
continu
contract
control
controversi
convent
convers
convict
convinc
cook
cool
cooper
cop
cope
cops
core
corner
corp
corpor
corporation
corps
corrupt
cost
costum
couldn
count
countri
country
countrymus
countrysid
coup
coupl
couple
courag
cours
court
courtcas
courteneycox
courtroom
cousin
cover
covert
cow
cowardli
cowboy
crab
crack
craft
craig
craigt
crash
crazi
creat
creation
creativ
creator
creatur
creatures
credit
crew
cri
crime
crimefight
crimes
crimin
criminal
criminals
crisi
crisis
critic
crocodil
crook
cross
crowd
crown
cruel
cruelti
cruis
crusad
crush
crystal
cuba
cubagoodingjr
culmin
cult
cultfilm
cultur
culture
cultureclash
cun
cup
cure
current
curs
curse
curtishanson
custodi
custom
cut
cuttingthecord
cyberpunk
cyborg
cynic
dad
daili
dakotafan
dale
damag
damon
dan
danaykroyd
danc
dancer
danger
danhedaya
daniel
danielcraig
danielday
danielradcliff
danni
danny
dannyboyl
dannydevito
dannyglov
dannyhuston
dannymcbrid
dannytrejo
dare
dark
darkcomedi
darkest
darylhannah
dash
date
daughter
dave
davi
david
davidarquett
davidcronenberg
davidcross
davidduchovni
davidfinch
davidgordongreen
davidkoechn
davidmors
davido
davidschwimm
davidspad
davidstrathairn
davidthewli
daxshepard
day
daydream
days
dc
dccomic
dea
dead
deadli
deaf
deal
dealer
dean
death
deathofafriend
deathoffath
deathpenalti
debramess
debt
debut
decad
decapit
deceas
deceit
decept
decid
decis
declar
dedic
deed
deep
deeper
deepli
defeat
defend
defens
defi
defin
deforestkelley
delight
deliv
deliveri
delroylindo
delus
demand
demimoor
demon
demonicpossess
demons
deni
deniserichard
denisleari
denni
dennisdugan
dennisfarina
dennishopp
dennisquaid
dentist
denzelwashington
depart
depend
depict
depress
depth
deputi
derang
derek
dermotmulroney
descend
describ
desert
design
desir
desol
despair
desper
despit
destin
destini
destiny
destroy
destroyed
destruct
destruction
detect
detective
determin
detroit
devast
develop
devic
devil
deviou
devis
devot
diabol
diagnos
dialogu
diamond
dian
dianekeaton
dianekrug
dianelan
diannewiest
diari
dick
dictat
did
didn
die
died
diego
diegoluna
dies
differ
different
difficult
dig
diner
dinner
dinosaur
diplomat
dire
direct
director
dirt
dirti
dirtycop
disabl
disappear
disappears
disast
disaster
disastr
discov
discoveri
diseas
disease
disfigur
disgrac
disguis
dishonesti
disillus
disney
disord
dispatch
disrupt
distant
district
distrust
disturb
ditch
diva
dive
divid
divis
divorc
divorce
dj
djimonhouns
dna
doc
doctor
document
documentari
dodg
doe
doesn
dog
doll
dollar
dolphin
dolphlundgren
domest
domin
dominicwest
don
donaldfaison
donaldpetri
donaldsutherland
doncheadl
donnel
doom
door
doubl
double
doublecross
doublelif
doubt
doug
dougliman
dougrayscott
dr
dracula
drag
dragon
drama
dramat
draw
drawn
dread
dream
dreams
dress
drew
drewbarrymor
drift
drifter
drink
drive
driven
driver
drop
drown
drug
drugabus
drugaddict
drugdeal
druglord
drugs
drugsmuggl
drugtraff
drugus
drunk
drunken
du
dualident
dub
duck
dude
duel
duke
dump
duo
dure
duringcreditssting
dustinhoffman
dutch
duti
dutton
dwarv
dwaynejohnson
dyinganddeath
dylan
dylanbak
dynam
dynasti
dysfunct
dysfunctionalfamili
dystopia
dystopicfutur
eager
earli
earlier
earn
earth
earthquak
easi
east
eat
eccentr
econom
economi
eddi
eddiegriffin
eddiemurphi
edg
edharri
editor
educ
edward
edwardburn
edwardnorton
effect
effort
egg
ego
egypt
egyptian
el
elabor
elderli
elect
element
eleph
elev
eliaskotea
elijahwood
elimin
elisabethshu
elit
elite
elizabeth
elizabethbank
elizabethperkin
ella
ellefan
ellenbarkin
ellenburstyn
ellenpag
elli
elliot
elliott
els
elud
elus
elv
elvi
embark
embassi
embroil
emerg
emigr
emilehirsch
emili
emilyblunt
emilymortim
emilywatson
emma
emmarobert
emmaston
emmathompson
emmawatson
emmetwalsh
emot
emperor
empire
employ
employe
enabl
encount
encourag
end
endless
endoftheworld
endur
enemi
enemies
enemy
energi
enforc
engag
engin
england
english
enigmat
enjoy
enlist
enorm
enrol
ensemblecast
ensu
ensues
ensur
entangl
enter
enterpris
entertain
entir
entiti
environ
environment
epic
epidem
episod
equal
era
eric
ericbana
ericrobert
erin
ernest
erotic
erupt
escap
escapad
escape
escapefromprison
escort
especi
espionag
establish
estat
estrang
etern
ethan
ethanhawk
ethic
eugenelevi
europ
european
eva
evacu
evad
evamend
evanrachelwood
eve
event
events
eventu
eventually
everi
everybodi
everyday
everyon
everyth
evid
evil
evolut
evolv
ewanmcgregor
ex
exact
exactli
examin
exchang
excit
exclus
execut
exercis
exhibit
exil
exist
existence
existenti
exorc
exot
exoticisland
expect
expected
expedit
experi
experienc
experiment
expert
explain
explod
exploit
explor
explos
expos
extra
extramaritalaffair
extraordinari
extraterrestri
extraterrestrialtechnolog
extrem
extremeviol
eye
eyes
fabl
fac
face
facil
fact
faction
factori
fade
fail
fairi
fairytal
faith
fake
falcon
fall
fallen
fallinginlov
fals
falseident
falselyaccus
fame
famili
families
family
familyrelationship
famkejanssen
famou
fan
fangvamp
fantasi
fantast
fantasyworld
far
farewel
farm
farmer
fascin
fashion
fast
faster
fat
fatal
fate
father
fatherdaughterrelationship
fathersonrelationship
favor
favorit
fbi
fbiagent
fear
fearless
fearsom
featur
fed
feder
feed
feel
feet
fellow
femal
female
femalecorps
femalefriendship
femalenud
femaleprotagonist
fend
festiv
festival
feud
fi
fiancé
fiction
fictionalplac
field
fierc
fifth
fight
fighter
figur
fil
file
film
filmdirector
filmmak
filmproduc
films
final
finale
financ
financi
fine
finish
finn
firm
fish
fisherman
fishoutofwat
fistfight
fit
fix
flame
flash
flashback
flat
fledgl
flee
flesh
fli
flight
fling
flint
flirt
flood
florida
florist
flower
flyingsauc
focu
focus
foe
foil
folk
follow
food
foot
footag
footbal
footchas
forbidden
forbiddenlov
forc
force
forces
ford
foreign
forest
forestwhitak
forev
forever
forg
forget
forgiv
form
formid
formula
fort
fortun
fortune
fortunetel
forward
foster
fought
foundfootag
fourth
fox
frame
franc
france
francesfish
francesmcdormand
francisco
francisfordcoppola
frank
frankcoraci
frankenstein
franki
franklangella
frankoz
frantic
fratern
fraud
freak
fred
freddi
freddieprinzejr
fredward
free
freedom
freez
french
frequent
fresh
freshman
friend
friendli
friends
friendship
frighten
frog
fromragstorich
frontier
frozen
frustrat
fu
fuel
fugit
fulfil
fulli
fun
fund
funer
funeral
furiou
futur
future
futurist
fword
ga
gabriel
gabrielbyrn
gabrielleunion
gabrielmacht
gadget
gaelgarcíabern
gain
galaxi
gambl
gambler
game
games
gandhi
gang
gangster
gangwar
garag
garden
garfield
gari
garrymarshal
garygray
garyoldman
garysinis
gasstat
gate
gather
gave
gay
gayrelationship
genehackman
gener
general
generation
genet
geniu
genius
gentl
geoffreyrush
georg
george
georgeclooney
georgew
georgia
gerardbutl
german
germani
germany
getaway
ghetto
ghost
giancarloesposito
giant
giantrobot
gift
gig
giovanniribisi
girl
girlfriend
girls
given
glamor
glass
glennclos
glenneheadli
global
globe
glori
goal
god
goe
gold
golden
golf
gone
good
goodvsevil
goranvisnj
gordon
gore
goreverbinski
gorgeou
gorilla
gossip
got
gotham
gothamc
gotten
govern
government
governor
gr
grace
grad
grade
gradual
graduat
grand
grandfath
grandfather
grandmoth
grandmother
grant
grave
great
greater
greatest
greec
greed
greedi
greek
green
greg
gregkinnear
gregorypeck
grew
grief
griev
griffin
grim
grip
grisli
ground
group
groupoffriend
grow
growingup
grown
gruesom
gu
guard
guardian
guerrilla
guest
guid
guilt
guitar
gun
gunfight
gunman
gunsling
guru
gusvans
guy
guypearc
guyritchi
guys
gwynethpaltrow
gym
gypsi
gérarddepardieu
ha
hack
hacker
hair
hal
haleyjoelos
half
hall
halleberri
halloween
hallucin
han
hand
handl
hands
handsom
handtohandcombat
hang
hankazaria
hannah
happen
happi
happili
happiness
happy
har
hara
harass
harbor
hard
harlem
harmoni
harold
haroldrami
harri
harriet
harrison
harrisonford
harrow
harry
harryconnickjr
harsh
hart
harvard
harvey
harveykeitel
hasn
hatch
hate
hatr
haunt
hauntedhous
haven
havoc
hawaii
haydenchristensen
haydenpanettier
haze
head
headlin
heal
health
hear
heard
heart
heartattack
heartbreak
heat
heather
heathergraham
heathledg
heaven
heavi
heavili
heavymet
height
heir
heiress
heist
held
helen
helenabonhamcart
helenhunt
helenmirren
helicopt
hell
help
henchmen
henri
hero
heroes
heroic
heroin
heroism
hi
hidden
hide
high
highest
highland
highli
highschool
highschoolsport
highschoolstud
highway
hijack
hilari
hilaryduff
hilaryswank
hill
himalaya
hip
hippi
hire
histor
histori
historicalfigur
history
hit
hitchhik
hitman
ho
hockey
hold
hole
holi
holiday
holli
hollyhunt
hollywood
home
homeinvas
homeland
homeless
homelessperson
hometown
homicid
homosexu
honey
honeymoon
hong
hongkong
honor
hood
hoodlum
hook
hop
hope
hopedavi
hopelessli
hopper
hord
horribl
horrif
horrifi
horror
hors
horsebackrid
horserac
hospit
hospital
host
hostag
hostage
hostil
hot
hotel
hotelroom
hotshot
hour
hous
house
household
housewif
howard
howev
hud
huge
hugh
hughgrant
hughjackman
hughlauri
hugoweav
human
humananimalrelationship
humanity
humankind
humans
humili
humor
hundr
hunger
hungri
hunt
hunter
husband
hustler
hypnosi
hypnot
hyun
ianholm
ianmckellen
ianmcshan
ice
icecub
icon
idea
ideal
idealist
ident
identity
idol
idriselba
idyl
ignit
ignor
ii
iii
il
ill
illeg
illegaldrug
illegalimmigr
illegalprostitut
illness
imag
imagin
imaginari
imagined
imax
immedi
immens
immigr
immort
impact
imperi
imperson
implic
import
imposs
impostor
impress
imprison
inadvert
incest
incid
includ
increas
increasingli
incred
independ
independentfilm
indi
india
indian
indiana
indianlead
individu
industri
industry
inexplic
infam
infant
infect
infidel
infiltr
influenc
inform
inhabit
inherit
initi
inject
injur
injuri
inmat
inner
innoc
insan
insecur
insid
insight
insist
insomnia
inspector
inspir
instal
instant
instantli
instead
instinct
institut
institution
instructor
insur
insurg
intellig
intend
intens
intent
intergalact
intern
internet
interpret
interrog
interspeciesrom
intertwin
interview
intim
intoler
intrigu
introduc
invad
invas
invent
inventor
invest
investig
investigate
invis
invit
involv
iowa
ira
iran
iranian
iraq
iraqwar
ireland
irish
iron
isaiahwashington
islam
island
isn
isol
isra
israel
issu
itali
italian
ivanreitman
jack
jackass
jackblack
jacki
jackiechan
jackieearlehaley
jacknicholson
jackson
jadapinkettsmith
jade
jail
jake
jakegyllenha
jame
james
jamescaan
jamescromwel
jamesfranco
jamesgandolfini
jamesmangold
jamesmarsden
jamesmcavoy
jamesremar
jamesspad
jameswood
jami
jamiebel
jamiefoxx
jamieleecurti
jane
japan
japanes
jaredleto
jason
jasonbateman
jasonbigg
jasonisaac
jasonle
jasonmew
jasonrobard
jasonschwartzman
jasonsegel
jasonstatham
jasonsudeiki
javierbardem
jay
jaybaruchel
jaychandrasekhar
jayroach
jazz
jealousi
jean
jeanreno
jedi
jeff
jeffbridg
jeffdaniel
jeffgoldblum
jeffreytambor
jeffreywright
jenamalon
jennif
jenniferaniston
jenniferconnelli
jennifergarn
jenniferjasonleigh
jenniferlawr
jenniferlopez
jenniferlovehewitt
jeremyiron
jeremynortham
jeremypiven
jeremyrenn
jerri
jersey
jerusalem
jess
jessebradford
jesseeisenberg
jessica
jessicaalba
jessicabiel
jessicachastain
jessicalang
jesu
jesus
jesuschrist
jetli
jew
jewel
jewish
jigsaw
jill
jim
jimbelushi
jimbroadb
jimcarrey
jimcaviezel
jimmi
jimmy
jimmybennett
jimsturgess
jin
joanallen
joanchen
joancusack
joaquinphoenix
job
jobinterview
jock
jodiefost
joe
joel
joelcoen
joeledgerton
joelkinnaman
joelschumach
joepantoliano
joepesci
joey
john
johnc
johncarpent
johnclees
johncusack
johngoodman
johnhawk
johnheard
johnhurt
johnkrasinski
johnleguizamo
johnlithgow
johnmalkovich
johnmctiernan
johnni
johnny
johnnydepp
johnnyknoxvil
johnson
johntravolta
johnturturro
join
jon
jonahhil
jonathan
jonathanfrak
jonathanrhysmey
jone
jones
jonfavreau
jonvoight
jordan
joseph
josephfienn
josephgordon
josh
joshbrolin
joshhartnett
joshhutcherson
joshluca
journal
journalist
journey
joy
jr
juan
judelaw
judg
judidench
judygr
juli
julia
julian
juliannemoor
juliansand
juliarobert
juliastil
julie
julieandrew
juliettelewi
jump
jungl
jungle
junior
junki
just
justic
justice
justinlong
justintimberlak
kalpenn
kansa
karat
karen
karlurban
kat
kate
katebeckinsal
katebosworth
katehudson

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity = cosine_similarity(vectors)

In [39]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.2850557338444825)),
 (507, np.float64(0.25231028011870793)),
 (3728, np.float64(0.2506402059138015)),
 (582, np.float64(0.24194822861802104)),
 (539, np.float64(0.24019223070763068))]

In [40]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [41]:
recommend('Avatar')

Aliens vs Predator: Requiem
Independence Day
Falcon Rising
Battle: Los Angeles
Titan A.E.

In [42]:
import pickle
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))